theme: jekyll-theme-hacker

title: Home
description: Josh Beto
permalink: none

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"