# metadata
title: Joshua-Beto
bio: Software Developer

# styling
theme: jekyll-theme-hacker

# page configs
permalink: none
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"